# Generated by Django 2.1.4 on 2018-12-22 07:26

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_strides', picklefield.fields.PickledObjectField(default=(5, 7, 9), editable=False)),
                ('static_th', models.FloatField(default=10)),
                ('norep_std_th', models.FloatField(default=13)),
                ('norep_ent_th', models.FloatField(default=1.0)),
                ('inrep_std_th', models.FloatField(default=13)),
                ('inrep_ent_th', models.FloatField(default=1.1)),
                ('lastsix_ent_th', models.FloatField(default=1.1)),
                ('history_num', models.IntegerField(default=9)),
                ('in_time', models.IntegerField(default=0)),
                ('out_time', models.IntegerField(default=0)),
                ('cooldown_in_time', models.IntegerField(default=0)),
                ('cooldown_out_time', models.IntegerField(default=0)),
                ('global_counter', models.IntegerField(default=0)),
                ('winner_stride', models.IntegerField(default=0)),
                ('cur_state', models.IntegerField(default=0)),
                ('in_frame_num', models.IntegerField(default=-1)),
                ('actions_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LocalCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField()),
                ('rep_count', models.IntegerField(default=0)),
                ('frame_residue', models.IntegerField(default=0)),
                ('count_array', picklefield.fields.PickledObjectField(editable=False)),
                ('ent_arr', picklefield.fields.PickledObjectField(editable=False)),
                ('std_arr', picklefield.fields.PickledObjectField(editable=False)),
                ('label_array', picklefield.fields.PickledObjectField(editable=False)),
                ('global_counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repetition_count_server.GlobalCounter')),
            ],
        ),
    ]
